apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    essential-containers: "main"
  name: ng
spec:
  containers:
  - image: busybox
    name: sidecar
    command: ["/bin/sh"]
    args: ["-c", "sleep 600"]
  - image: busybox
    name: main
    command: ["/bin/sh"]
    args: ["-c", "sleep 120"]
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
